class { "vmbuildhelper::ntp": }
class { "vmbuildhelper::git": }
class { "vmbuildhelper::yum": }
class { "vmbuildhelper::dnsresolver": }
class { "vmbuildhelper::apache": }
class { "vmbuildhelper::firewall": }
class { "vmbuildhelper::php": }
class { "vmbuildhelper::mysql": }
class { "vmbuildhelper::phpmyadmin": }
class { "vmbuildhelper::memcached": }
class { "vmbuildhelper::rubygems": }
class { "vmbuildhelper::env": }
class { "vmbuildhelper::users": }
class { "vmbuildhelper::vsftpd": }
class { "vmbuildhelper::nfs": }
class { "vmbuildhelper::supervisord": }
class { "vmbuildhelper::cron": }
class { "vmbuildhelper::execs": }